//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestivalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bands
    {
        public int ID { get; set; }
        public string naam { get; set; }
        public string omschrijving { get; set; }
        public string fotoUri { get; set; }
    }
}
