//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestivalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gebruikers
    {
        public int ID { get; set; }
        public string vnaam { get; set; }
        public string anaam { get; set; }
        public string email { get; set; }
        public string wachtwoord { get; set; }
        public Nullable<byte> isAdmin { get; set; }
    }
}
