//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestivalWeb.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int ID { get; set; }
        public string soort { get; set; }
        public int aantal { get; set; }
        public Nullable<double> prijs { get; set; }
    }
}
